-- MySQL Script generated by MySQL Workbench
-- Dom 04 Jun 2017 00:32:09 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `lang` CHAR(12) NULL,
  `cellphone` VARCHAR(25) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feed` (
  `idFeed` VARCHAR(25) NOT NULL,
  `tweet` TEXT(140) NULL,
  `favorite` TINYINT(1) NULL,
  `User_idUser` VARCHAR(25) NOT NULL,
  `data` VARCHAR(14) NULL,
  PRIMARY KEY (`idFeed`, `User_idUser`),
  INDEX `fk_Feed_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Feed_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Followers` (
  `User_idUser` VARCHAR(25) NOT NULL,
  `Folower` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`User_idUser`, `Folower`),
  CONSTRAINT `fk_Followers_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Following`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Following` (
  `User_idUser` VARCHAR(25) NOT NULL,
  `Followed` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`User_idUser`, `Followed`),
  INDEX `fk_Following_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Following_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hashtags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hashtags` (
  `ind` INT NOT NULL AUTO_INCREMENT,
  `Feed_idFeed` VARCHAR(25) NOT NULL,
  `Feed_User_idUser` VARCHAR(25) NOT NULL,
  `tag` VARCHAR(25) NULL,
  PRIMARY KEY (`ind`, `Feed_idFeed`, `Feed_User_idUser`),
  INDEX `fk_Hashtags_Feed1_idx` (`Feed_idFeed` ASC, `Feed_User_idUser` ASC),
  CONSTRAINT `fk_Hashtags_Feed1`
    FOREIGN KEY (`Feed_idFeed` , `Feed_User_idUser`)
    REFERENCES `mydb`.`Feed` (`idFeed` , `User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
